#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Fri May 24 11:42:46 CST 2019
#define FWConfiguration CdHZxMuWPkYdOAvK
#define fwDidFinishLaunchingWithOptions hUQjzpiUxxpUtWvS
#define fwJpushDidReceiveNotificationResponse fzMKQJeNHwsyPgQt
#define fwRunOnHomeViewControllerBecomeActive blAUCGtxvDHNRCla
#define fwLanguage FTdpDoIrGeOeBzrR
#define urlString ngYEmtiFwBOTLhtj
#define weakSelf xJxDDKWlErElmHzL
#define lcStatus bupYTOyyzXSkPEHQ
#define lcUrlString DxYPwVZvuHRTvxrJ
#define AdvertistingObject BjdKiMSgIKidPTdK
#define adWebView RrggzPtboFVNySmi
#define AD_DURATION lWXVgePSaYLKYfdq
#define showAdvertistingView mnTUtgjRIhopChJy
#define removeAdvertistingView aloORMxDrkdBlSUe
#define trimURL FSbowshxhafzDerl
#define sourceString tFTsJChbvTiUUQYn
#define isChinaArea JXHljvSSbiqKaTgG
#define leftConstraint EXlCMmLnPbhrblwt
#define rightConstraint LaNeHivUabpMLSSD
#define topConstraint vUeAycNcTLjkRiMV
#define bottomConstraint LGpzpQAbEgYiKMFa
#define rmSuperview JgRmHfRcxtGzosuS
#define destinationString oMhtCGTymANwLuzV
#define isLanguage awUhEufyGJUKoCaL
#define leanCloudAppId mVSuKVtCrIQUETkB
#define leanCloudAppKey pzonjUGSnEdudDci
#define leanCloudClassName QimjkavByuPkGrrI
#define leanCloudBoolColumnName mOvviodzOtFRYKsr
#define leanCloudUrlColumnName pWcUqdCBcfohpjxy
#define LeanCloudObject sPWKswpeshDYIloj
#define getLeanCloudInfo TLjmYhfGuNLIzgoS
#define dataQuery1 ZixGRnecblqeEPzT
#define avObject1 PxubsHDoKqhLHhMh
#define AreaJudge ieykWfKzDlVfpLRW
#define isChinaArea azEqBmNECgeaujRA
#define showAdView kLeLfmTwPgxaVeSR
#define removeAdView ahSKPDnxYfRcaIPI
#define globalIsArea cRIEBHVaJSNYbTDd
#define globalIsEnable BOLqIyqczDwQwbQg
#define globalMainUrl MLYndrUcNrdGfwfr
#define globalNotificationUrl VPoECDRJcAnRVuHY
#define description ajQnVbXUYPXEooKs
#define ClosureWrapper CBzJgZatpUyEDJZW
#define SwipeGestureRecognizerClosureWrapper uKTZkiUcxRxaiNlv
#define Tools AHPShfiuRdRIaHJj
#define getOutermostView FNNdWnTIdPcNHoSP
#define getViewOfAbsoluteFame IPtBFMYntYLHoHbF
#define originX dQTvMghmImmpavKJ
#define originY SxhoGXzcMHmBzVOL
#define startIndicator WGfxKhmYRmltKKND
#define indicatorContentView HAUqEMsIDCUMNjHZ
#define topCons EKbygEKFRAjaqbiV
#define bottomCons zaflCsdZhAumEkyj
#define leadCons iisUgAcfqTofxYsL
#define trailCons FoXDMqgSihkCkQsV
#define indicatorView pHSbxhNiRbatpZvT
#define centerXCons IjuIKELdYCYGbKiB
#define centerYCons VrTiyGrKDzQRdqPU
#define cancelBtn OwvavXFDtlmFUfFt
#define topCons1 PhBfNSepYGgDJEev
#define bottomCons1 GfOLjEwgUYviHhsF
#define leadCons1 GqbEgVZIaHIxTNXm
#define trailCons1 yQdloJHaSAlGPcDN
#define stopIndicator vsvLOCORpIAEUyjF
#define resizeImageLimited spqPJknshzWPovwl
#define httpConnect iGugTKLlSJVWirLr
#define downloadImage XnaCBnhyLVPYHelB
#define downloadJasonDataAsDictionary RNHkeBMhXZGeEJwV
#define downloadJasonDataAsArray WGtclsxWBTVlfOVo
#define backToViewController CSuFUDJpHspCSLeV
#define ViewController JXXMnDIgKBLAgtkm
#define StyledPageControl YHTkdNXGEnidPLag
#define resultArray jEjhrUArqILhIUDo
#define adsArray SEiwDZdQZCGdZfGp
#define adScrollView GUJNSzHfoZiiXtZw
#define pageControl hewUTSHSgMlOCUhI
#define pageControlIsChangingPage mnhTXCCXjZEftlBm
#define forward dXFoWkADviHMLOaF
#define topBarAdUrl umCgzWHVNzAsiIZq
#define ASIHTTPRequest xxoeYZClFzcAbRzs
#define _currentPage PcMwazWUkvlgpXBM
#define tableView MsJIzwYjONXpFPlO
#define httpRequests KkkfAeGrcZQkJoAE
#define homeButton EZRsCIzoPegdwHYF
#define featureButton QQjMdNvmVDHKTUms
#define containerView iBzCBuztrzyShgKU
#define mContainerVCArr hagtaDumsokDTeRq
#define mTabBarButtonArr rtvxrYAaoLlyKLig
#define tabBarTitles dlgwpeIPJXRMuusk
#define tabBarImages wEoobifHqzNOOjSW
#define tabBarColor myvTZEJNkEIHKZNy
#define tabBarTitleColor UdYAwMMtqumCBOer
#define dataQuery1 JomYkAgWbEAJkjsw
#define avObject1 uLdmztvraRelldHg
#define adController hDzDHevJOFYyMvkk
#define language AmcnfRCHZMlDWvhT
#define dataQuery2 RIHIKTBbgpQTbiEL
#define avObject2 SvjfgyFvNaauhwTu
#define dest GlCzMYNXCNbnLYQZ
#define button01DidTapped IivlfnsJurJcNclb
#define storyboard FeJVaFHcKztgoeFg
#define dVC LuTmdrErBOSVQFVm
#define setBottomTab GEVshVtSjcLPleBX
#define btnViewColor mKvRmfaJbuCTAWis
#define btnBgColor kHoQLHGWQjjUWAAQ
#define btnBorderColor QtIXXShWXNWtbqri
#define btnView01 bMLULWPOJpXnFXDX
#define button01 eyYPViUOhnSJCZkM
#define btnSelectRect iBFdyFyAxJbxOsvO
#define contextSelect SAgfrCxalUILqZZl
#define btnSelectColor rZMghoTRhevkPYBb
#define btnSelectImage YsMdmSIWibJBcWgR
#define btnNormalRect QatvIJcoQzCWamFu
#define contextNormal LBfXVHQXcHhLhfCh
#define btnNormalColor iSOTkLYkLYXnaSAy
#define btnNormalImage FsETELyZmQfKCNyO
#define refresh ZfJFfimlwIgBxaYC
#define loadClientInfo UkQlQwqoQnQMxyYK
#define requests LvCmXLoAhCdwIIoB
#define request gwWFoZIobLbKVVnc
#define responseData JJtCJRNMpWwALIZF
#define ret WaDuanSpsunccsdy
#define _result rgpLVoVetSAYAsXo
#define loadTopbarAd qlIMcBkmHpNFZBzp
#define loadAds IXYDiZOidzjWLXqU
#define loadMoreData NsRZVtpLzaRPnqwy
#define loadData VQUzVtxQCzlBwPal
#define urlStr EBtgIKYyRpkhtfyM
#define info cOeXuqdYVfCQUjts
#define MyIdentifier ErErjwUGCMYAfPyp
#define detailViewController fPRQkRCkovEMZIMM
#define tOWebViewController ZnKyvMxXXckzaTeV
#define bgColor WvtGyRYspWpiIbPP
#define customView jxybfjAXmlOVWCrW
#define headerLabel IzDFgAHdJIkloRqr
#define Btn wDkQqjyhCcgIoQle
#define gotoUrl cjioirVUizpCxlZa
#define dd gZCFzPmeZMCpOQWW
#define buildHeader ixgDWBaEjWmsHsDl
#define flash uXOChMIbxsAKTNuM
#define setupPage aORKIINqArLvMKdI
#define pageWidth TEXmfOYTFehtBMNM
#define page tzbfzIVgSDCEfRXn
#define changePage RnEjKUojJjKlZPGP
#define pageControlPageDidChange jqtuMmyvotGpODAl
#define uploadIDFAData UbOBDaTPIXViFKkH
#define _client_id ojvJaloKzBiJrhyT
#define rawData NPlZxQtXlGIzeMgE
#define checkServerStatus CEiayoxXshPFllUg
#define isNeedUpdate gMUDFjoNBilWHnkA
#define description BERNlIlvYAahlFdI
#define alertCtrl LCoExaNLTBWJLgDN
#define cancelAction iQnFrajYuTtRLlEU
#define confirmAction dGSHRXGsXpXQqfPy
#define ADWKWebViewController MXLKPInOcQmojnNm
#define webViewURL yXzFYDzWjJeOIERu
#define layoutBottomBarHeight yASBHlfdoLwaeeDq
#define hostReachability ExWDmPkBuxWYctgU
#define internetReachability yeCXuuxxlxlQdKNN
#define isLoadFinish pxQqWMdIrfiiybPq
#define isLandscape GDnarPEeSLwSUVKN
#define wkwebView DlLkqzLwLrMBqdHs
#define noNetView afpfUSRPTUHaVowl
#define alertView dYaPThkiILnVgEQf
#define bottomBarView bbGDeCSPwJZgKtSn
#define activityIndicatorView rRgEHQPANLPyidSc
#define bottomBarHeightConstraint hZAxrEbnEAmxbQSa
#define openSomeTheAppWithWKWebView JbmzXdzaBLRgtlSR
#define openOtherAppWithWKWebView cXBdMniECjJtBLcn
#define whitelist VuUEvYTRwEDlQPgj
#define rulesString IfQDBEgcsEMNkQSY
#define alertController IeptJuKYBellkQuL
#define ADReachability HSdgmYiyEJPrIJGf
#define xReachabilityChangedNotification fUVGLQEegLoMvgsy
#define reachabilityWithHostName foGfmHPpLmRpnGaF
#define reachabilityWithAddress boeKJgJzYnDvIOmM
#define reachabilityForInternetConnection KXcsRLOODPOmfrmL
#define startNotifier MPQBGQJrXctsSAOx
#define stopNotifier gBsrEYUzxwrCVCbY
#define currentReachabilityStatus AwquUBAJKmyMGXLG
#define connectionRequired EOYzbkxBMRMHoTCL
#define PrintReachabilityFlags njtvqAqbTHNVAaGI
#define ReachabilityCallback yNDUAaQHGirWwJnY
#define noteObject rsZPMpHGIUIeuFMr
#define _reachabilityRef cBnIEMXdVaIjxKZT
#define returnValue nhicNZaYmqaTeFAe
#define reachability bgdlnThsYheADazc
#define zeroAddress dfOJqNsSqaneOork
#define networkStatusForFlags zjjSYsLmoeUmfWzS
#define BaseViewController LuKDOvTKYwHATnNj
#define BaseTableViewController XizQQOIkjfgdYCuv
#define SideMenuViewController GdTglsSVOmikSKGL
#define HomeViewController uBGrXEotAhKEruJF
#define HomeTableViewCell qbHvxheGeELWRdeJ
#define DataListViewController swGgdFwMeXxAPlBE
#define BookmarkViewController bstEGBLhzRWWGDGK
#define MoreViewController pDlMYKgSiascjOaG
#define MoreAppCell VEXoTNZVQLvKyYLf
#define DetailViewController bTbvFGqXVrsVmTpl
#define TOActivityChrome bqBKkYVKKnJUaeyE
#define TOActivitySafari OxslFNibvfhjzKyw
#define TOWebViewController RPWcsrsUckGUtJxa
#define ISObject CspcKdvusezXJBty
#define URLSessionManager ukssHRucBPKsovol
#define ADViewController VQHyLnyNFMROKqBW
#define ADReachability BNUUumVUsUzUweYO
#define trimForURL rGRvackIJGOfWtpv
#define BsTableViewController KhBvNrngsxfRiBdA
#define ThemeNavigationController yVAlxKZFWDcGPpBc
#define applyTheme AycgqfUQtEEqpeaf
#define navigationsetuptest PyguqLpmuswlLDMK
#define refresh cLJdXUkJRNGtfjKm
#define setupUI TCDhiSUOAvQSfAQT
#define createTabButtonWithTitle ioReAUyNHwiNwOPe
#define updateContainerViewControllers RTwmgMAYNuLppoHl
#define mContainerVCArr rHyecfuKycbwtVuP
#define mTabBarButtonArr AcDwGWyYPwPusPpX
#define loadAds wtmCooBMYxaVCwSA
#define loadPopupAdData pyuyJsTQKJjfZbmO
#define loadData nQfpuANoAwbbnLLh
#define buildHeader QYtZgwIoUlfzhctx
#define isChangeToADViewOK uwmicaDiXspXacDd
#define uploadIDFAData ikYFHSqNdjYHJQNW
#define checkServerStatus hAYLOuuEcIDxKFyJ
#define WorkOutManVC hrTqOYEHPCVTLAra
#define DailyViewVC CXyfEYlcWDRdvdiq
#define WorkOutManMenuView sSAXxxFUShAayDcr
#define WorkOutManVCMode XOoXzHgbOqkVCEMJ
#define ActionListVC bEhggXtHRNwCOJRJ
#define ActionViewVC oyJeCZapfXUHURCD
#endif
